---
- hosts: all
  roles:
    - role: ansible-role-postgresql
      postgresql_users_databases:
      - user: alice
        password: alice123
        databases: [publicdb, secretdb]
      - user: bob
        password: bob123
        databases: [publicdb]
        roles: "CREATEDB,NOSUPERUSER"
      - user: charles
        password: charles123
        databases: [publicdb]
        privs: "SELECT"
        # roles: "LOGIN,NOCREATEDB,NOCREATEROLE,NOCREATEUSER,NOINHERIT,NOREPLICATION,NOSUPERUSER"

- hosts: all
  tasks:
    - name: create test tables
      command: env PGPASSWORD=alice123 psql -h localhost -U alice publicdb -c "{{ item }}"
      register: result
      changed_when: "not ('skipping' in result.stderr or '0 0' in result.stdout)"
      with_items:
          - "create table if not exists regular (text text primary key);"
          - "insert into regular select ('clear text') where not exists (select text from regular);"
          - "create table if not exists password (text text primary key);"
          - "insert into password select ('PRIVATE!') where not exists (select text from password);"
