---
# tasks file for ome.postgresql

- name: postgres | setup repository
  become: true
  yum:
    name: "{{ postgresql_repourl }}"
    state: present

- name: postgres | install client packages
  become: true
  yum:
    name: "{{ postgresql_basename }}"
    state: present

- name: postgres | install server packages
  become: true
  yum:
    name: "{{ postgresql_basename }}-server"
    state: present
  when: postgresql_install_server

- name: postgres | install extension packages
  become: true
  yum:
    name: "{{ postgresql_basename }}-contrib"
    state: present
  when: postgresql_install_extensions

- name: postgres | set permissions on data directory
  become: true
  file:
    owner: postgres
    group: postgres
    path: "{{ postgresql_datadir }}"
    recurse: true
    state: directory
  when: postgresql_install_server and postgresql_server_chown_datadir

- name: >-
    postgres | initialise PostgreSQL cluster (skip if data directory
    already exists)
  become: true
  command: "{{ postgresql_bindir }}/{{ postgresql_setupname }} initdb"
  args:
    creates: "{{ postgresql_datadir }}/PG_VERSION"
  environment:
    PGSETUP_INITDB_OPTIONS: --encoding=UTF8 --locale=en_US.UTF-8 --auth-host=md5
  when: postgresql_install_server

- name: postgres | postgresql config file
  become: true
  become_user: postgres
  template:
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    src: postgresql-conf.j2
  notify:
    - restart postgresql
  when: postgresql_install_server

- name: postgres | configure client authorisation
  become: true
  become_user: postgres
  template:
    dest: "{{ postgresql_datadir }}/pg_hba.conf"
    src: pg_hba-conf.j2
  notify:
    - restart postgresql
  when: postgresql_install_server

- name: postgres | start service
  become: true
  service:
    enabled: true
    name: postgresql-{{ postgresql_version }}
    state: started
  when: postgresql_install_server

- include: databases.yml
  when: postgresql_install_server
